title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://code1133.github.io/ocg-docs/

aux_links:
  Template Repository: https://github.com/Code1133/ocg-docs/
