name: Question/Support
description: Ask a question or get support for using OCG
title: "[Question]: "
labels: ["question", "support"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using OCG? We're here to help! Please provide as much context as possible.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What category does your question fall under?
      options:
        - Installation/Setup
        - Level Generation
        - Configuration
        - Integration
        - Performance
        - Troubleshooting
        - Best Practices
        - Unreal Engine Compatibility
        - Other
    validations:
      required: true

  - type: input
    id: unreal-version
    attributes:
      label: Unreal Engine Version
      description: What version of Unreal Engine are you using?
      placeholder: e.g., 5.5, 5.4.4, 5.3.2
    validations:
      required: false

  - type: input
    id: ocg-version
    attributes:
      label: OCG Version
      description: What version of OCG are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context/Background
      description: Provide any relevant context or background information
      placeholder: |
        What are you trying to achieve?
        What have you tried so far?
        Any relevant project details?
    validations:
      required: false

  - type: textarea
    id: code-samples
    attributes:
      label: Code Samples (if applicable)
      description: Share any relevant code or configuration
      placeholder: Paste any relevant code here
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: Add screenshots if they help explain your question
      placeholder: Drag and drop screenshots here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the documentation for an answer
          required: true
        - label: I have searched existing issues for similar questions
          required: true
