// Copyright (c) 2025-2026 Code1133. All rights reserved.
#pragma once

#include "Stats/Stats.h"

DECLARE_STATS_GROUP(TEXT("OCG"), STATGROUP_OCG, STATCAT_Advanced)

DECLARE_CYCLE_STAT_EXTERN(TEXT("HeightMap Generate"),   STAT_OCG_HeightMapGenerate,   STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("TempMap Generate"),     STAT_OCG_TempMapGenerate,     STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("HumidityMap Generate"), STAT_OCG_HumidityMapGenerate, STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Biome Decide"),         STAT_OCG_BiomeDecide,         STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Biome Blend"),          STAT_OCG_BiomeBlend,          STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Smooth GaussianBlur"),  STAT_OCG_SmoothGaussian,      STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Smooth SpikeRemove"),   STAT_OCG_SmoothSpike,         STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Smooth Median"),        STAT_OCG_SmoothMedian,        STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Erosion Pass"),         STAT_OCG_ErosionPass,         STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Erosion Brush Init"),   STAT_OCG_ErosionBrushInit,    STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Landscape Modify"),     STAT_OCG_LandscapeModify,     STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("River PathFind"),       STAT_OCG_RiverPathFind,       STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Population Foliage"),   STAT_OCG_PopulationFoliage,   STATGROUP_OCG, ONEBUTTONLEVELGENERATION_API)
