# OCG Documentation Configuration
title: OCG Documentation
description: Documentation for the One-Click Level Generator (OCG) project, providing an overview of its features, usage, and technical details.
favicon_ico: "/assets/favicons/favicon.ico"

url: https://code1133.github.io
baseurl: /ocg
repository: https://github.com/Code1133/ocg/

theme: just-the-docs
color_scheme: dark
permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

# Footer content configuration
footer_content: "Copyright &copy; 2025 Code1133 | All rights reserved."

# Auxiliary links configuration
aux_links:
  Docs Repository: https://github.com/Code1133/ocg/
  Issues: https://github.com/Code1133/ocg/issues
aux_links_new_tab: true

# Callouts configuration
callouts:
  info:
    title: Information
    color: blue
  warning:
    title: Warning
    color: orange
  danger:
    title: Danger
    color: red
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow

callouts_opacity: 0.2

# Search settings
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"
